image: iquiw/alpine-emacs


pages:
  stage: deploy
  script:
  - emacs --batch --load publish.el
  - ls -lR
  artifacts:
    paths:
    - workshops
    - reveal.js
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
