#+AUTHOR: Operating System Applications
#+OPTIONS: timestamp:nil date:nil toc:nil num:nil
#+REVEAL_ROOT: ../../reveal.js
#+REVEAL_TRANS: slide
#+REVEAL_THEME: black
#+REVEAL_EXTRA_CSS: ../custom.css

* Basics of =python=

** Launching python
#+BEGIN_SRC sh -i
$ python3
Python 3.6.4 (default, Jan  5 2018, 02:35:40)
[GCC 7.2.1 20171224] on linux
Type "help", "copyright", "credits" or "license"
for more information.
>>> _
#+END_SRC

** Print to standard output
#+BEGIN_SRC python -i
print("Hello, World!")
#+END_SRC

** Taking input
#+BEGIN_SRC python -i
testCase = input("Enter a test case: ")
#+END_SRC

** Loops
#+BEGIN_SRC python -i :results output :exports both
for i in [4, 2, 3, 3]:
    print(i)
#+END_SRC

#+RESULTS:
: 4
: 2
: 3
: 3

** Slices in String
#+BEGIN_SRC python -i :results output :exports both
s = "Hello"
print("0", s)
print("1", s[2])
print("2", s[1:3])
print("3", s[:3])
print("4", s[2:])
#+END_SRC

#+RESULTS:
: Hello
: l
: el
: Hel
: llo

** List Datatype
#+BEGIN_SRC python -i
l = [1, 5, 2, 24]
l = range(20)
l = range(5, 21, 5)
#+END_SRC

** Dictionaries
#+BEGIN_SRC python -i :results output :exports both
d = {"x": 2, "y": 3, 4: 5}
print(d)
print(d["x"])
# print(d[3])
print(d[4])
#+END_SRC

#+RESULTS:
: {'x': 2, 'y': 3, 4: 5}
: 2
: 5

** Defining functions
#+BEGIN_SRC python -i
def isPrime(n):
    if n < 2:
        return False
    else if n == 2:
        return True
    else if n % 2 == 0:
        return False
    else:
        for i in range(3, int(n ** i) + 1, 2):
            if (n % i == 0):
                return False
        return True
#+END_SRC

** Mysterious ~__name__~
#+ATTR_REVEAL: :frag (appear)
+ Carries the name of the current module
+ File under execution has the value ~__main__~

*** =myModule.py=
#+BEGIN_SRC python -i :tangle myModule.py :results output :exports code
print(__name__)
#+END_SRC
Run:
#+ATTR_REVEAL: :frag (appear)
#+BEGIN_SRC sh :exports code
$ python3 myModule.py
#+END_SRC
Output:
#+ATTR_REVEAL: :frag (appear)
#+BEGIN_SRC text
__main__
#+END_SRC

*** =other.py=
#+BEGIN_SRC python -i :tangle other.py :results output :exports code
import myModule
print(__name__)
#+END_SRC
Run:
#+ATTR_REVEAL: :frag (appear)
#+BEGIN_SRC sh :exports code
$ python3 other.py
#+END_SRC
Output:
#+ATTR_REVEAL: :frag (appear)
#+BEGIN_SRC text
myModule
__main__
#+END_SRC

* File Handling in Python

** Contents of =filename.txt=
#+BEGIN_EXAMPLE
There is some text

You can write more of it
And enjoy
#+END_EXAMPLE

** Reading a file
#+BEGIN_SRC python -i :results output :exports both
f = open("filename.txt", "r")
print(f.read(2))
print(f.readline())
print(f.readline())
print(f.readline())
f.close()
#+END_SRC

#+RESULTS:
: There is some text
:
: You can write more of it
: And enjoy
:

** Read all at once
#+BEGIN_SRC python -i :results output :exports both
f = open("filename.txt", "r")  # Open in read mode
print(f.read())
f.close()
#+END_SRC

** Writing to a file
#+BEGIN_SRC python -i
f = open("file.txt", "w")  #Open in write mode
f.write("I don't need an editor.")
f.close()
#+END_SRC

* Lambda functions
#+ATTR_REVEAL: :frag (appear)
+ Also known as anonymous functions
+ One line only
+ Used for defining in place functions
+ Syntax:
  #+BEGIN_SRC python -i
square = lambda x: x * x
square(4)
  #+END_SRC

** Merits of lambda
#+ATTR_REVEAL: :frag (appear)
+ It gets the work done
+ If the function definitions are short

** =makeInc= using =lambda=
#+BEGIN_SRC python -i :exports code :session incsession
def makeInc(m):
    return (lambda n: n + m)
#+END_SRC

#+RESULTS:

** Using =makeInc=
#+BEGIN_SRC python -i :cache yes :results output :session incsession
incBy2 = makeInc(2)
incBy3 = makeInc(3)
print(incBy2(7))
print(incBy3(32))
#+END_SRC
Output:
#+RESULTS[e7590c3681bff4355674536d266540ff74c8dfc9]:
: 9
: 35

** What is missing?
+ Lambda is good in *lisp* like languages and *JavaScript*
+ But not particularly in python
+ Cannot write multiple statements

** Are we done with it?

** Implementing better lambdas
#+BEGIN_SRC python -i :exports code
def makeInc(m):
    def inc(n):
        nonlocal m
        return n + m
    return inc
#+END_SRC

** Write a =mySort= function
#+ATTR_REVEAL: :frag (appear)
+ Which can sort both increasing and decreasing order on demand
+ Having the following function parameters:
#+ATTR_REVEAL: :frag (appear)
  + =list= to be sorted
  + =compare= to change the order

* Operating system
** How do we do it?
Python provides an interface to the operating system through the =os=
library of functions which contains several system calls to *retrieve*
and *manipulate* different parts of operating system.
#+ATTR_REVEAL: :frag (appear)
#+BEGIN_SRC python -i
import os
#+END_SRC

** What is a process?
*It is an instance of a computer program that is being executed.* A
process in execution requires a processing unit(like CPU) to run the
instructions as specified in the program.
#+BEGIN_SRC python -i
import os
os.exec
os.fork
os.wait
#+END_SRC
** What is forking?
#+ATTR_REVEAL: :frag (appear)
+ A way of cloning processes.
+ Continues execution from the next line.
* Structure and Interpretation of Computer Programming
